### ISSUE TITLE
Support timezone configuration

### ISSUE THREAD

**Issue by jumbosushi** [HirokiCHIBA/timerange-clipboard#1]
Thanks for making this extension 🙌 

I have a feature request. Our dashboards are in UTC timezone, but I believe this extension converts millisecond epoch to local timezone. It would be great if we can add a config option to set global (for all apps) or app-specific timezone so the UI will show time in a configured timezone

![CleanShot 2022-04-01 at 15 55 56](https://user-images.githubusercontent.com/9669739/161352201-fef8767c-7db4-4c57-9820-91f536474c9b.png)

**Comment by HirokiCHIBA** [comment]
@jumbosushi  Thanks for the good suggestion!
It certainly seems useful if we work based on a different timezone than local timezone. I will include such a feature in the next update :+1:

**Comment by HirokiCHIBA** [comment]
The feature for this issue is implemented at #2 and released at [v1.1.0](https://github.com/HirokiCHIBA/timerange-clipboard/releases/tag/v1.1.0). (also available in [Chrome Web Store](https://chrome.google.com/webstore/detail/timerange-clipboard/gbofkihmogiigjdalkplkjheholghbfc))

Feel free to let me know if you have any additional requests!
